// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./src/components/AdvertiseBox.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IHeroiconsSolidPaperClip: typeof import('~icons/heroicons-solid/paper-clip')['default']
    ILogosVue: typeof import('~icons/logos/vue')['default']
    ITwemoji1stPlaceMedal: typeof import('~icons/twemoji/1st-place-medal')['default']
    ITwemoji2ndPlaceMedal: typeof import('~icons/twemoji/2nd-place-medal')['default']
    ITwemoji3rdPlaceMedal: typeof import('~icons/twemoji/3rd-place-medal')['default']
  }
}

export { }
