// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./src/components/AdvertiseBox.vue')['default']
    AppFooter: typeof import('./src/components/app/AppFooter.vue')['default']
    AppMenu: typeof import('./src/components/app/AppMenu.vue')['default']
    AppProfile: typeof import('./src/components/app/AppProfile.vue')['default']
    AppSubmenu: typeof import('./src/components/app/AppSubmenu.vue')['default']
    AppTopbar: typeof import('./src/components/app/AppTopbar.vue')['default']
    Foo: typeof import('./src/components/basic/Foo.vue')['default']
    Hello: typeof import('./src/components/basic/Hello.vue')['default']
  }
}

export { }
