/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./components/AdvertiseBox.vue')['default']
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppMenu: typeof import('./components/app/AppMenu.vue')['default']
    AppProfile: typeof import('./components/app/AppProfile.vue')['default']
    AppSubmenu: typeof import('./components/app/AppSubmenu.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    Foo: typeof import('./components/basic/Foo.vue')['default']
    Hello: typeof import('./components/basic/Hello.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
