/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvertiseBox: typeof import('./components/AdvertiseBox.vue')['default']
    AppColorMode: typeof import('./components/app/AppColorMode.vue')['default']
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppProfile: typeof import('./components/app/AppProfile.vue')['default']
    AppSidebar: typeof import('./components/app/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    Foo: typeof import('./components/basic/Foo.vue')['default']
    Hello: typeof import('./components/basic/Hello.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TipTap: typeof import('./components/tiptap/TipTap.vue')['default']
  }
}
